### ISSUE TITLE
Blazor at work with Microsoft Entra ID (including how to from scratch) Source

### ISSUE THREAD

**Issue by dshaverPIH** [thedevtalkshow/BlazorAuthFromScratch#1]
Would it be possible to get the code from the Blazor at work live stream committed?

**Comment by SpaceShot** [comment]
Thanks for the comment... I'm planning to work on this over the weekend in prep for next week.  Sorry it has been delayed.

**Comment by SpaceShot** [comment]
Committed the code to add components and api endpoints that will work for google and microsoft entra id.

This code is deliberately verbose and repetitive.  The idea is to make it easy to understand how to do these things, and you may refactor and redesign as needed.
